<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SettingsLeaveTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now()->toDateTimeString();

        $types = [
            [
                'id'                       => 1,
                'name'                     => 'السنوية',
                'days'                     => 21,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 5,
                'days_after_threshold'     => 30,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 1,
                'gender_applicability'     => 'both',
                'min_service_years'        => 0,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 0,
                'is_carry_forwardable'     => 1,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 2,
                'name'                     => 'الزواج',
                'days'                     => 5,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 0,
                'gender_applicability'     => 'both',
                'min_service_years'        => 0,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 3,
                'name'                     => 'إجازة المولود الجديد',
                'days'                     => 3,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 0,
                'gender_applicability'     => 'both',
                'min_service_years'        => 0,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 4,
                'name'                     => 'إجازة الوفاة',
                'days'                     => 5,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 0,
                'gender_applicability'     => 'both',
                'min_service_years'        => 0,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 5,
                'name'                     => 'الإجازة المرضية',
                'days'                     => 30,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 0,
                'gender_applicability'     => 'both',
                'min_service_years'        => 0,
                'has_attachments'          => 1,
                'attachment_description'   => 'التقرير الطبي - مستند من المستشفى',
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 6,
                'name'                     => 'إجازة الحج',
                'days'                     => 15,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 0,
                'gender_applicability'     => 'both',
                'min_service_years'        => 2,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 1,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 7,
                'name'                     => 'إجازة الوضع للمرأة العاملة',
                'days'                     => 70,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 0,
                'gender_applicability'     => 'female',
                'min_service_years'        => 0,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 8,
                'name'                     => 'إجازة العدة للمرأة المسلمة',
                'days'                     => 130,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 0,
                'gender_applicability'     => 'female',
                'min_service_years'        => 0,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 9,
                'name'                     => 'إجازة الامتحانات الدراسية',
                'days'                     => null,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 0,
                'gender_applicability'     => 'both',
                'min_service_years'        => 0,
                'has_attachments'          => 1,
                'attachment_description'   => 'جدول الامتحانات',
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 10,
                'name'                     => 'الإجازة بدون أجر',
                'days'                     => null,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 0,
                'is_deductible'           => 0,
                'gender_applicability'     => 'both',
                'min_service_years'        => 0,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 11,
                'name'                     => 'إجازة سنوية نصف يوم',
                'days'                     => null,
                'leave_unit_type'          => 'half_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 1,
                'gender_applicability'     => 'both',
                'min_service_years'        => 0,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 12,
                'name'                     => 'إجازة المحكمة',
                'days'                     => null,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 0,
                'gender_applicability'     => 'both',
                'min_service_years'        => 0,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
            [
                'id'                       => 13,
                'name'                     => 'العمل عن بعد',
                'days'                     => null,
                'leave_unit_type'          => 'full_day',
                'service_years_threshold'  => 0,
                'days_after_threshold'     => 0,
                'status'                   => 'active',
                'is_paid'                  => 1,
                'is_deductible'           => 0,
                'gender_applicability'     => 'both',
                'min_service_years'        => 0,
                'has_attachments'          => 0,
                'attachment_description'   => null,
                'max_requests'             => 0,
                'is_carry_forwardable'     => 0,
                'user_id'                  => 1,
                'start_date'               => null,
                'end_date'                 => null,
                'created_at'               => $now,
                'updated_at'               => $now,
                'deleted_at'               => null,
            ],
        ];

        DB::table('settings_leave_types')->insert($types);
    }
}
